
export default {
	REQUEST_DATA                :'REQUEST_DATA',
	
	RECEIVE_DATA                :'RECEIVE_DATA',
	USERENCRYPT                 :'USERENCRYPT',
	FETCHIMITATE_DATA           :'FETCHIMITATE_DATA',
	FETCHEVENTREPORT            :'FETCHEVENTREPORT',
	FETCHUNUSUAL                :'FETCHUNUSUAL',
	FETCHAllSENSORLIST          :'FETCHAllSENSORLIST',
	// FETCHQUERYSENSORLIST        :'FETCHQUERYSENSORLIST',
	FETCHQUERYMONITOR           :'FETCHQUERYMONITOR',
	FETCHQUERYMONITORFILTER     :'FETCHQUERYMONITORFILTER'
	
}